### ISSUE TITLE
Collision error when after menu screen

### ISSUE THREAD

**Issue by thatguytimtam** [the-bald-lad/Pygame-asteroids#5]
Hey I was intrested in checking out your game but when I started it up I got the following error 

return o1.mask.overlap(o2.mask, (offset_x, offset_y)) != None
TypeError: integer argument expected, got float

The temporary fix I found was to round the offset x and y to the nearest integer but it was just to let you know and I bet there is a better way to go about it:

`return o1.mask.overlap(o2.mask, (round(offset_x), round(offset_y))) != None`

**Comment by the-bald-lad** [comment]
Hello, I couldn't replicate the bug after trying quite a few things. I'm going to implement your suggested fix as it doesn't seem to break anything and should solve your issue. Cheers
